CREATE TABLE IF NOT EXISTS {{PRE}}users (
    id_user int(11) NOT NULL AUTO_INCREMENT,
    fid_account int(11) NOT NULL,
    fid_media int(11) NOT NULL,
    user_username varchar(64) NOT NULL,
    user_password varchar(128) NOT NULL,
    user_level int(11) NOT NULL,
    user_type varchar(2) NOT NULL,
    user_expires date NOT NULL,
    user_fname varchar(64) NOT NULL,
    user_lname varchar(64) NOT NULL,
    user_address1 varchar(128) NOT NULL,
    user_address2 varchar(128) NOT NULL,
    user_city varchar(64) NOT NULL,
    user_state varchar(64) NOT NULL,
    user_zip varchar(12) NOT NULL,
    user_email varchar(128) NOT NULL,
    user_phone varchar(20) NOT NULL,
    user_signup TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
    user_login DATETIME NOT NULL,
    PRIMARY KEY (id_user),
    KEY fid_account (fid_account,fid_media),
    KEY user_username (user_username),
    KEY user_type (user_type),
    KEY user_expires (user_expires),
    KEY user_email (user_email),
    KEY user_signup (user_signup),
    KEY user_login (user_login)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci AUTO_INCREMENT=1 ;